<a href="https://colab.research.google.com/github/0Pixel0/Numpy-Tutorial/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

*An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.*



In [2]:
a=np.array([1,2,3,4,5]);
print(a);

[1 2 3 4 5]


**array has axes for 2d it has 2 axes.**

In [3]:
a=np.zeros(2);

a=np.ones(2);

#create an empty array
a=np.empty(2);
print(a);

#create with range
a1=np.arange(4);
a2=np.arange(2,8,2);#start,end,jump
print(a1,a2);

[0. 0.]
[0 1 2 3] [2 4 6]


In [4]:
#use linspace
a=np.linspace(0,10,6);
# give a linearly seperated array -start,end,size.
a

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [5]:
# dtype
a=np.ones(2,dtype=np.bool_);
# bool_,str_,int32,int64,complex_,......
a

array([ True,  True])

In [6]:
a=np.random.rand(2,4);
# random generation
a

array([[0.76217738, 0.58509237, 0.32243984, 0.48338654],
       [0.50802843, 0.70774689, 0.4108995 , 0.33514966]])

In [7]:
a=np.array([4,2,1]);
a=np.sort(a);
print(a);

# concatenate.
a=np.array([[1,2,3]]);
b=np.array([[0,9,4]]);
c=np.concatenate((a,b));#needs double bracket.
d=np.concatenate((a,b),axis=1);#concatenates along the axis 1
print(d);
print(c);

[1 2 4]
[[1 2 3 0 9 4]]
[[1 2 3]
 [0 9 4]]


In [8]:
a=np.array([[1,2,3],[4,5,6]]);
a.ndim#gives the dimension of the array.

a.size#gives the total elements in the np array

a.shape#description about the dimensions.

(2, 3)

In [9]:
#reshape
a=np.arange(1,7);
a=a.reshape((2,3));
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a=np.arange(1,10);
print(a[1:]);#example of slicing
print(a[-2:]);

#satisfying a specific condition
c=((a>3) & (a%2==0));#for perfect working use brackets for both conditions
print(a[c]);


[2 3 4 5 6 7 8 9]
[8 9]
[4 6 8]


In [25]:
a=np.arange(1,21).reshape(4,5);
print(a);
#hsplit use to split the array equally.
print(np.hsplit(a,5));

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]]), array([[ 5],
       [10],
       [15],
       [20]])]


#Basic operations on array


In [32]:
#add
a=np.ones((2,3));
b=np.arange(1,7).reshape(2,3);
# print(a+b);#just use the +,same goes for -,*,/.


# for sum of elements in np arr
print(b.sum());
print(b.sum(axis=0));#col
print(b.sum(axis=1));#row

21
[5 7 9]
[ 6 15]


# operations b/w scaler and vector a.k.a broadcasting

In [33]:
a=np.array([2.9,1.5]);
print(a*1.2);

[3.48 1.8 ]


---
*NumPy also performs aggregation functions. In addition to min, max, and sum, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.*

---



In [37]:
print(a.min());
print(a.max());
print(a.mean());
print(a.std());
#can also specify axis.

1.5
2.9
2.2
0.7


**Random**

In [48]:
#either use np.random.normal
rng=np.random.default_rng();
a=rng.integers(2,5,size=(2,3));
print(a);

[[3 2 4]
 [2 3 3]]
3


**Unique values,indices,count**

In [54]:
a=np.random.default_rng().integers(2,8,size=(1,5));
print(a);
print(np.unique(a));
print(np.unique(a,return_index=True,return_counts=True));


[[3 7 4 5 7]]
[3 4 5 7]
(array([3, 4, 5, 7]), array([0, 2, 3, 1]), array([1, 1, 1, 2]))


**transpose**

In [56]:
a=np.arange(1,9).reshape(2,4);
a=a.T
print(a)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


flipping /reversing contents


In [64]:
a=np.arange(1,10);
a=np.flip(a);
print(a);
a=np.flip(a);
a=a.reshape((3,3))
# print(a);
a=np.flip(a,axis=1);
print(a);

[9 8 7 6 5 4 3 2 1]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [67]:
#flatten
a=np.arange(1,10).reshape(3,3);
b=a.flatten();
print(a);
print(b);

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


# MATH

In [73]:
#rmse
a=np.random.default_rng().integers(1,9,size=(1,5));
b=np.random.default_rng().integers(1,9,size=(1,5));

print("a:",a);
print("b:",b);

n=a.size;
err=(1/n)*np.sum(np.square(a-b));
err

a: [[2 2 7 4 5]]
b: [[1 6 4 5 2]]


7.2

*Further topics to read about:*
* dtypes
* more methods to create np arrays
* saving np arrays
* broadcasting